LibraryManagement: LibraryManagement.ConversionUtility Class Reference
LibraryManagement.ConversionUtility Class Reference
Static Public Member Functions
static byte[] ToByte (this string hexString)
static string ToHex (this byte[] arr)
static bool IsHex (this string str)
static int GetInt (this byte[] data, int offset, int length)
static string ToAscii (this string hexString)
static int ByteArrayToInteger (byte[] byteArray)
static byte[] IntegerToByteArray (int value)
static byte[] StringListToByteArray (List< string > array, int itemMaxCount, int itemMaxLength)
static List< string > ByteArrayToStringList (byte[] byteArray, int itemMaxCount, int itemMaxLength)
static byte[] StringToByteArray (string data)
static string ByteArrayToString (byte[] byteArray)
Member Function Documentation
ByteArrayToInteger()
static int LibraryManagement.ConversionUtility.ByteArrayToInteger (byte[] byteArray) static
Referenced by LibraryManagement.Book.ByteArrayBlockToBook().
ByteArrayToString()
static string LibraryManagement.ConversionUtility.ByteArrayToString (byte[] byteArray) static
Referenced by LibraryManagement.Book.ByteArrayBlockToBook(), LibraryManagement.Category.ByteArrayBlockToCategory(), and LibraryManagement.ConversionUtility.ByteArrayToStringList().
ByteArrayToStringList()
static List< string > LibraryManagement.ConversionUtility.ByteArrayToStringList (byte[] byteArray, int itemMaxCount, int itemMaxLength) static
References LibraryManagement.ConversionUtility.ByteArrayToString().
Referenced by LibraryManagement.Book.ByteArrayBlockToBook().
GetInt()
static int LibraryManagement.ConversionUtility.GetInt (this byte[] data, int offset, int length) static
IntegerToByteArray()
static byte[] LibraryManagement.ConversionUtility.IntegerToByteArray (int value) static
Referenced by LibraryManagement.Book.BookToByteArrayBlock().
IsHex()
static bool LibraryManagement.ConversionUtility.IsHex (this string str) static
StringListToByteArray()
static byte[] LibraryManagement.ConversionUtility.StringListToByteArray (List< string > array, int itemMaxCount, int itemMaxLength) static
References LibraryManagement.ConversionUtility.StringToByteArray().
Referenced by LibraryManagement.Book.BookToByteArrayBlock().
StringToByteArray()
static byte[] LibraryManagement.ConversionUtility.StringToByteArray (string data) static
Referenced by LibraryManagement.Book.BookToByteArrayBlock(), LibraryManagement.Category.CategoryToByteArrayBlock(), and LibraryManagement.ConversionUtility.StringListToByteArray().
ToAscii()
static string LibraryManagement.ConversionUtility.ToAscii (this string hexString) static
ToByte()
static byte[] LibraryManagement.ConversionUtility.ToByte (this string hexString) static
ToHex()
static string LibraryManagement.ConversionUtility.ToHex (this byte[] arr) static
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-dll/ConversionUtility.cs