LibraryManagement: LibraryManagement.Category Class Reference
LibraryManagement.Category Class Reference
Public Member Functions
Category ()
Static Public Member Functions
static byte[] CategoryToByteArrayBlock (Category category)
static Category ByteArrayBlockToCategory (byte[] byteArray)
Static Public Attributes
const int CATEGORY_NAME_LENGTH = 40
const int CATEGORY_MAX_LENGTH = CATEGORY_NAME_LENGTH
Properties
string Name [get, set]
Private Attributes
string _name
Constructor & Destructor Documentation
Category()
LibraryManagement.Category.Category ()
Referenced by LibraryManagement.Category.ByteArrayBlockToCategory().
Member Function Documentation
ByteArrayBlockToCategory()
static Category LibraryManagement.Category.ByteArrayBlockToCategory (byte[] byteArray) static
References LibraryManagement.ConversionUtility.ByteArrayToString(), LibraryManagement.Category.Category(), LibraryManagement.Category.CATEGORY_MAX_LENGTH, LibraryManagement.Category.CATEGORY_NAME_LENGTH, and LibraryManagement.Category.Name.
Referenced by LibraryManagement.LibraryManager.ReadCategory().
CategoryToByteArrayBlock()
static byte[] LibraryManagement.Category.CategoryToByteArrayBlock (Category category) static
References LibraryManagement.Category.CATEGORY_MAX_LENGTH, LibraryManagement.Category.CATEGORY_NAME_LENGTH, LibraryManagement.Category.Name, and LibraryManagement.ConversionUtility.StringToByteArray().
Referenced by LibraryManagement.LibraryManager.InsertCategory(), and LibraryManagement.LibraryManager.UpdateCategory().
Member Data Documentation
_name
string LibraryManagement.Category._name private
CATEGORY_MAX_LENGTH
const int LibraryManagement.Category.CATEGORY_MAX_LENGTH = CATEGORY_NAME_LENGTH static
Referenced by LibraryManagement.Category.ByteArrayBlockToCategory(), LibraryManagement.Category.CategoryToByteArrayBlock(), LibraryManagement.LibraryManager.DeleteCategory(), librarianApp.LibraryManager.App.ListCategory(), librarianApp.LibraryManager.App.ListCategoryForAddBook(), LibraryManagement.LibraryManager.ReadCategory(), and LibraryManagement.LibraryManager.UpdateCategory().
CATEGORY_NAME_LENGTH
const int LibraryManagement.Category.CATEGORY_NAME_LENGTH = 40 static
Referenced by LibraryManagement.Category.ByteArrayBlockToCategory(), and LibraryManagement.Category.CategoryToByteArrayBlock().
Property Documentation
Name
string LibraryManagement.Category.Name get set
Referenced by LibraryManagement.Category.ByteArrayBlockToCategory(), LibraryManagement.Category.CategoryToByteArrayBlock(), librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.ListCategory(), and librarianApp.LibraryManager.App.ListCategoryForAddBook().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-dll/Category.cs