LibraryManagement: librarianApp.LibraryManager.App Class Reference
librarianApp.LibraryManager.App Class Reference
Public Member Functions
void Start ()
Private Member Functions
void RunMainMenu ()
void DisplayBook ()
void DisplayCtg ()
void AddCategory ()
void ListCategory ()
void ListCategoryForAddBook ()
void EditCategory ()
void DeleteCategory ()
void DisplayBorrowHistory ()
void DisplayAbout ()
void DisplayOptions ()
void ExitApp ()
Member Function Documentation
AddCategory()
void librarianApp.LibraryManager.App.AddCategory () inline private
References librarianApp.LibraryManager.App.DisplayCtg().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
DeleteCategory()
void librarianApp.LibraryManager.App.DeleteCategory () inline private
References librarianApp.LibraryManager.App.DisplayCtg().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
DisplayAbout()
void librarianApp.LibraryManager.App.DisplayAbout () inline private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
DisplayBook()
void librarianApp.LibraryManager.App.DisplayBook () inline private
References librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.ListCategoryForAddBook(), librarianApp.LibraryManager.Menu.Run(), and librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.DisplayBook(), and librarianApp.LibraryManager.App.RunMainMenu().
DisplayBorrowHistory()
void librarianApp.LibraryManager.App.DisplayBorrowHistory () inline private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
DisplayCtg()
void librarianApp.LibraryManager.App.DisplayCtg () inline private
References librarianApp.LibraryManager.App.AddCategory(), librarianApp.LibraryManager.App.DeleteCategory(), librarianApp.LibraryManager.App.EditCategory(), librarianApp.LibraryManager.App.ListCategory(), librarianApp.LibraryManager.Menu.Run(), and librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.AddCategory(), librarianApp.LibraryManager.App.DeleteCategory(), librarianApp.LibraryManager.App.EditCategory(), librarianApp.LibraryManager.App.ListCategory(), and librarianApp.LibraryManager.App.RunMainMenu().
DisplayOptions()
void librarianApp.LibraryManager.App.DisplayOptions () inline private
References librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.Menu.Run(), and librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.DisplayOptions(), and librarianApp.LibraryManager.App.RunMainMenu().
EditCategory()
void librarianApp.LibraryManager.App.EditCategory () inline private
References librarianApp.LibraryManager.App.DisplayCtg().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
ExitApp()
void librarianApp.LibraryManager.App.ExitApp () inline private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
ListCategory()
void librarianApp.LibraryManager.App.ListCategory () inline private
References librarianApp.LibraryManager.App.DisplayCtg().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
ListCategoryForAddBook()
void librarianApp.LibraryManager.App.ListCategoryForAddBook () inline private
Referenced by librarianApp.LibraryManager.App.DisplayBook().
RunMainMenu()
void librarianApp.LibraryManager.App.RunMainMenu () inline private
References librarianApp.LibraryManager.App.DisplayAbout(), librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.DisplayBorrowHistory(), librarianApp.LibraryManager.App.DisplayCtg(), librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.App.ExitApp(), and librarianApp.LibraryManager.MainMenu.Run().
Referenced by librarianApp.LibraryManager.App.DisplayAbout(), librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.DisplayBorrowHistory(), librarianApp.LibraryManager.App.DisplayCtg(), librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.App.ExitApp(), and librarianApp.LibraryManager.App.Start().
Start()
void librarianApp.LibraryManager.App.Start () inline
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.Program.Main().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-application/Program.cs