LibraryManagement: LibraryManagement.LibraryManager Class Reference
LibraryManagement.LibraryManager Class Reference
Static Public Member Functions
static bool IsNumeric (object Expression)
static void InsertBook (Book book)
static void InsertCategory (Category category)
static void UpdateBook (Book book, int booknumber)
static void UpdateCategory (Category category, int catnumber)
static void DeleteBook (int booknumber)
static void DeleteCategory (int catnumber)
static Book ReadBook (int booknumber)
static Category ReadCategory (int catnumber)
Member Function Documentation
DeleteBook()
static void LibraryManagement.LibraryManager.DeleteBook (int booknumber) static
References LibraryManagement.Book.BOOK_DATA_BLOCK_SIZE, LibraryManagement.FileUtility.DeleteBlock(), LibraryManagement.FileUtility.ReadBlock(), and LibraryManagement.FileUtility.UpdateBlock().
Referenced by librarianApp.LibraryManager.App.DisplayBook().
DeleteCategory()
static void LibraryManagement.LibraryManager.DeleteCategory (int catnumber) static
References LibraryManagement.Category.CATEGORY_MAX_LENGTH, LibraryManagement.FileUtility.DeleteBlock(), LibraryManagement.FileUtility.ReadBlock(), and LibraryManagement.FileUtility.UpdateBlock().
Referenced by librarianApp.LibraryManager.App.DeleteCategory().
InsertBook()
static void LibraryManagement.LibraryManager.InsertBook (Book book) static
References LibraryManagement.FileUtility.AppendBlock(), and LibraryManagement.Book.BookToByteArrayBlock().
Referenced by librarianApp.LibraryManager.App.DisplayBook().
InsertCategory()
static void LibraryManagement.LibraryManager.InsertCategory (Category category) static
References LibraryManagement.FileUtility.AppendBlock(), and LibraryManagement.Category.CategoryToByteArrayBlock().
Referenced by librarianApp.LibraryManager.App.AddCategory().
IsNumeric()
static bool LibraryManagement.LibraryManager.IsNumeric (object Expression) static
Referenced by librarianApp.LibraryManager.App.DisplayBook().
ReadBook()
static Book LibraryManagement.LibraryManager.ReadBook (int booknumber) static
References LibraryManagement.Book.BOOK_DATA_BLOCK_SIZE, LibraryManagement.Book.ByteArrayBlockToBook(), and LibraryManagement.FileUtility.ReadBlock().
Referenced by librarianApp.LibraryManager.App.DisplayBook().
ReadCategory()
static Category LibraryManagement.LibraryManager.ReadCategory (int catnumber) static
References LibraryManagement.Category.ByteArrayBlockToCategory(), LibraryManagement.Category.CATEGORY_MAX_LENGTH, and LibraryManagement.FileUtility.ReadBlock().
Referenced by librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.ListCategory(), and librarianApp.LibraryManager.App.ListCategoryForAddBook().
UpdateBook()
static void LibraryManagement.LibraryManager.UpdateBook (Book book, int booknumber) static
References LibraryManagement.Book.BOOK_DATA_BLOCK_SIZE, LibraryManagement.Book.BookToByteArrayBlock(), and LibraryManagement.FileUtility.UpdateBlock().
Referenced by librarianApp.LibraryManager.App.DisplayBook().
UpdateCategory()
static void LibraryManagement.LibraryManager.UpdateCategory (Category category, int catnumber) static
References LibraryManagement.Category.CATEGORY_MAX_LENGTH, LibraryManagement.Category.CategoryToByteArrayBlock(), and LibraryManagement.FileUtility.UpdateBlock().
Referenced by librarianApp.LibraryManager.App.EditCategory().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-dll/LibraryManager.cs