LibraryManagement: LibraryManagement.FileUtility Class Reference
LibraryManagement.FileUtility Class Reference
Static Public Member Functions
static bool DeleteFile (string path)
static byte[] ReadBlock (int count, int blocksize, string path)
static bool AppendBlock (byte[] data, string path)
static bool UpdateBlock (byte[] data, int count, int blocksize, string path)
static bool DeleteBlock (int count, int blocksize, string path)
Member Function Documentation
AppendBlock()
static bool LibraryManagement.FileUtility.AppendBlock (byte[] data, string path) static
Referenced by LibraryManagement.LibraryManager.InsertBook(), and LibraryManagement.LibraryManager.InsertCategory().
DeleteBlock()
static bool LibraryManagement.FileUtility.DeleteBlock (int count, int blocksize, string path) static
Referenced by LibraryManagement.LibraryManager.DeleteBook(), and LibraryManagement.LibraryManager.DeleteCategory().
DeleteFile()
static bool LibraryManagement.FileUtility.DeleteFile (string path) static
Referenced by librarianApp.LibraryManager.App.DisplayOptions().
ReadBlock()
static byte[] LibraryManagement.FileUtility.ReadBlock (int count, int blocksize, string path) static
Referenced by LibraryManagement.LibraryManager.DeleteBook(), LibraryManagement.LibraryManager.DeleteCategory(), librarianApp.LibraryManager.App.DisplayBook(), LibraryManagement.LibraryManager.ReadBook(), and LibraryManagement.LibraryManager.ReadCategory().
UpdateBlock()
static bool LibraryManagement.FileUtility.UpdateBlock (byte[] data, int count, int blocksize, string path) static
Referenced by LibraryManagement.LibraryManager.DeleteBook(), LibraryManagement.LibraryManager.DeleteCategory(), librarianApp.LibraryManager.App.DisplayBook(), LibraryManagement.LibraryManager.UpdateBook(), and LibraryManagement.LibraryManager.UpdateCategory().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-dll/FileUtility.cs