LibraryManagement: librarianApp.LibraryManager.App Class Reference
librarianApp.LibraryManager.App Class Reference
Public Member Functions
void Start ()
Private Member Functions
void RunMainMenu ()
void DisplayBook ()
void DisplayCtg ()
void AddCategory ()
void ListCategory ()
void ListCategoryForAddBook ()
void EditCategory ()
void DeleteCategory ()
void DisplayBorrowHistory ()
void DisplayAbout ()
void DisplayOptions ()
void ExitApp ()
Member Function Documentation
AddCategory()
void librarianApp.LibraryManager.App.AddCategory () private
References librarianApp.LibraryManager.App.DisplayCtg(), and LibraryManagement.LibraryManager.InsertCategory().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
DeleteCategory()
void librarianApp.LibraryManager.App.DeleteCategory () private
References LibraryManagement.LibraryManager.DeleteCategory(), and librarianApp.LibraryManager.App.DisplayCtg().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
DisplayAbout()
void librarianApp.LibraryManager.App.DisplayAbout () private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
DisplayBook()
void librarianApp.LibraryManager.App.DisplayBook () private
References LibraryManagement.Book.Abstract, LibraryManagement.Book.Authors, LibraryManagement.Book.BOOK_DATA_BLOCK_SIZE, LibraryManagement.Book.BookToByteArrayBlock(), LibraryManagement.Book.ByteArrayBlockToBook(), LibraryManagement.Book.CatalogId, LibraryManagement.Book.Categories, LibraryManagement.Book.City, LibraryManagement.LibraryManager.DeleteBook(), LibraryManagement.Book.Description, librarianApp.LibraryManager.App.DisplayBook(), LibraryManagement.Book.Edition, LibraryManagement.Book.Editors, LibraryManagement.Book.Given, LibraryManagement.Book.Id, LibraryManagement.LibraryManager.InsertBook(), LibraryManagement.LibraryManager.IsNumeric(), librarianApp.LibraryManager.App.ListCategoryForAddBook(), LibraryManagement.Category.Name, LibraryManagement.Book.Pages, LibraryManagement.Book.Price, LibraryManagement.Book.Publisher, LibraryManagement.Book.RackNo, LibraryManagement.FileUtility.ReadBlock(), LibraryManagement.LibraryManager.ReadBook(), LibraryManagement.LibraryManager.ReadCategory(), LibraryManagement.Book.Return, LibraryManagement.Book.RowNo, librarianApp.LibraryManager.Menu.Run(), librarianApp.LibraryManager.App.RunMainMenu(), LibraryManagement.Book.Status, LibraryManagement.Book.Tags, LibraryManagement.Book.Title, LibraryManagement.FileUtility.UpdateBlock(), LibraryManagement.LibraryManager.UpdateBook(), LibraryManagement.Book.Url, and LibraryManagement.Book.Year.
Referenced by librarianApp.LibraryManager.App.DisplayBook(), and librarianApp.LibraryManager.App.RunMainMenu().
DisplayBorrowHistory()
void librarianApp.LibraryManager.App.DisplayBorrowHistory () private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
DisplayCtg()
void librarianApp.LibraryManager.App.DisplayCtg () private
References librarianApp.LibraryManager.App.AddCategory(), librarianApp.LibraryManager.App.DeleteCategory(), librarianApp.LibraryManager.App.EditCategory(), librarianApp.LibraryManager.App.ListCategory(), librarianApp.LibraryManager.Menu.Run(), and librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.AddCategory(), librarianApp.LibraryManager.App.DeleteCategory(), librarianApp.LibraryManager.App.EditCategory(), librarianApp.LibraryManager.App.ListCategory(), and librarianApp.LibraryManager.App.RunMainMenu().
DisplayOptions()
void librarianApp.LibraryManager.App.DisplayOptions () private
References LibraryManagement.FileUtility.DeleteFile(), librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.Menu.Run(), and librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.DisplayOptions(), and librarianApp.LibraryManager.App.RunMainMenu().
EditCategory()
void librarianApp.LibraryManager.App.EditCategory () private
References librarianApp.LibraryManager.App.DisplayCtg(), and LibraryManagement.LibraryManager.UpdateCategory().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
ExitApp()
void librarianApp.LibraryManager.App.ExitApp () private
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.LibraryManager.App.RunMainMenu().
ListCategory()
void librarianApp.LibraryManager.App.ListCategory () private
References LibraryManagement.Category.CATEGORY_MAX_LENGTH, librarianApp.LibraryManager.App.DisplayCtg(), LibraryManagement.Category.Name, and LibraryManagement.LibraryManager.ReadCategory().
Referenced by librarianApp.LibraryManager.App.DisplayCtg().
ListCategoryForAddBook()
void librarianApp.LibraryManager.App.ListCategoryForAddBook () private
References LibraryManagement.Category.CATEGORY_MAX_LENGTH, LibraryManagement.Category.Name, and LibraryManagement.LibraryManager.ReadCategory().
Referenced by librarianApp.LibraryManager.App.DisplayBook().
RunMainMenu()
void librarianApp.LibraryManager.App.RunMainMenu () private
References librarianApp.LibraryManager.App.DisplayAbout(), librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.DisplayBorrowHistory(), librarianApp.LibraryManager.App.DisplayCtg(), librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.App.ExitApp(), and librarianApp.LibraryManager.MainMenu.Run().
Referenced by librarianApp.LibraryManager.App.DisplayAbout(), librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.DisplayBorrowHistory(), librarianApp.LibraryManager.App.DisplayCtg(), librarianApp.LibraryManager.App.DisplayOptions(), librarianApp.LibraryManager.App.ExitApp(), and librarianApp.LibraryManager.App.Start().
Start()
void librarianApp.LibraryManager.App.Start ()
References librarianApp.LibraryManager.App.RunMainMenu().
Referenced by librarianApp.Program.Main().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-application/Program.cs