LibraryManagement: librarianApp.LibraryManager.Menu Class Reference
librarianApp.LibraryManager.Menu Class Reference
Public Member Functions
Menu (string prompt, string[] options)
int Run ()
Private Member Functions
void DisplayOptions ()
Private Attributes
int SelectedIndex
string[] Options
string Prompt
Constructor & Destructor Documentation
Menu()
librarianApp.LibraryManager.Menu.Menu (string prompt, string[] options)
References librarianApp.LibraryManager.Menu.Options, librarianApp.LibraryManager.Menu.Prompt, and librarianApp.LibraryManager.Menu.SelectedIndex.
Member Function Documentation
DisplayOptions()
void librarianApp.LibraryManager.Menu.DisplayOptions () private
References librarianApp.LibraryManager.Menu.Options, librarianApp.LibraryManager.Menu.Prompt, and librarianApp.LibraryManager.Menu.SelectedIndex.
Referenced by librarianApp.LibraryManager.Menu.Run().
Run()
int librarianApp.LibraryManager.Menu.Run ()
References librarianApp.LibraryManager.Menu.DisplayOptions(), librarianApp.LibraryManager.Menu.Options, and librarianApp.LibraryManager.Menu.SelectedIndex.
Referenced by librarianApp.LibraryManager.App.DisplayBook(), librarianApp.LibraryManager.App.DisplayCtg(), and librarianApp.LibraryManager.App.DisplayOptions().
Member Data Documentation
Options
string [] librarianApp.LibraryManager.Menu.Options private
Referenced by librarianApp.LibraryManager.Menu.DisplayOptions(), librarianApp.LibraryManager.Menu.Menu(), and librarianApp.LibraryManager.Menu.Run().
Prompt
string librarianApp.LibraryManager.Menu.Prompt private
Referenced by librarianApp.LibraryManager.Menu.DisplayOptions(), and librarianApp.LibraryManager.Menu.Menu().
SelectedIndex
int librarianApp.LibraryManager.Menu.SelectedIndex private
Referenced by librarianApp.LibraryManager.Menu.DisplayOptions(), librarianApp.LibraryManager.Menu.Menu(), and librarianApp.LibraryManager.Menu.Run().
The documentation for this class was generated from the following file:
ce103-hw3-melih-divan/librarian-app-application/Program.cs